package org.king.security.domain;

import org.king.common.post.Post;
import org.king.department.bean.Department;

/**
 * AbstractAccount generated by MyEclipse - Hibernate Tools
 */

public class UsrPost extends org.king.framework.domain.BaseObject implements java.io.Serializable {


    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// Fields    

     private Integer id;
     private String usrId;
     private Integer dept = null;
     private Integer post = null;
     private Integer flag = 0;
     
     private Department deptObject;
     private Post postObject;
     
 	public String getUsrId() {
		return usrId;
	}
	public void setUsrId(String usrId) {
		this.usrId = usrId;
	}
	public Integer getDept() {		
		if(dept != null && dept.equals(0))
		{
			return null;
		}
		return dept;
	}
	public void setDept(Integer dept) {		
		this.dept = dept;		
	}
	public Integer getPost() {		
		if(post != null && post.equals(0))
		{
			return null;
		}
		return post;
	}
	public void setPost(Integer post) {
		this.post = post;			
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	
	@Override
	public boolean equals(Object arg0) {
		// TODO Auto-generated method stub
		if(arg0 instanceof UsrPost)
		{
			UsrPost up = (UsrPost)arg0;
			
			return up.getDept().equals(dept) && up.getPost().equals(post);
		}
		
		return false;
	}
	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
		return id.hashCode();
	}
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return null;
	}
	public Integer getFlag() {
		return flag;
	}
	public void setFlag(Integer flag) {
		this.flag = flag;
	}
	public Department getDeptObject() {
		return deptObject;
	}
	public void setDeptObject(Department deptObject) {
		this.deptObject = deptObject;
	}
	public Post getPostObject() {
		return postObject;
	}
	public void setPostObject(Post postObject) {
		this.postObject = postObject;
	}


   
}