package org.king.tender.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * DeviceList1st generated by MyEclipse - Hibernate Tools
 */

public class DeviceList1st extends org.king.framework.domain.BaseObject
		implements java.io.Serializable {

	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer dlfId;

	private Integer dlfTenderProjectId;

	private String dlfFirstEquipmentName;

	private Integer dlfSecondEquipmentCount;

	private Integer dlfStatus;

	private String dlfCreateUser;

	private Date dlfCreateTime;

	private String dlfUpdateUser;

	private Date dlfUpdateTime;
	
	private List<DeviceList2nd> devicList2ndList = new ArrayList<DeviceList2nd>();
	
	private List<DeviceListDetail> deviceListDetailList = new ArrayList<DeviceListDetail>();

	// Constructors

	/** default constructor */
	public DeviceList1st() {
	}

	/** minimal constructor */
	public DeviceList1st(Integer dlfStatus) {
		this.dlfStatus = dlfStatus;
	}

	/** full constructor */
	public DeviceList1st(Integer dlfTenderProjectId,
			String dlfFirstEquipmentName, Integer dlfSecondEquipmentCount,
			Integer dlfStatus, String dlfCreateUser, Date dlfCreateTime,
			String dlfUpdateUser, Date dlfUpdateTime) {
		this.dlfTenderProjectId = dlfTenderProjectId;
		this.dlfFirstEquipmentName = dlfFirstEquipmentName;
		this.dlfSecondEquipmentCount = dlfSecondEquipmentCount;
		this.dlfStatus = dlfStatus;
		this.dlfCreateUser = dlfCreateUser;
		this.dlfCreateTime = dlfCreateTime;
		this.dlfUpdateUser = dlfUpdateUser;
		this.dlfUpdateTime = dlfUpdateTime;
	}

	// Property accessors

	public Integer getDlfId() {
		return this.dlfId;
	}

	public void setDlfId(Integer dlfId) {
		this.dlfId = dlfId;
	}

	public Integer getDlfTenderProjectId() {
		return this.dlfTenderProjectId;
	}

	public void setDlfTenderProjectId(Integer dlfTenderProjectId) {
		this.dlfTenderProjectId = dlfTenderProjectId;
	}

	public String getDlfFirstEquipmentName() {
		return this.dlfFirstEquipmentName;
	}

	public void setDlfFirstEquipmentName(String dlfFirstEquipmentName) {
		this.dlfFirstEquipmentName = dlfFirstEquipmentName;
	}

	public Integer getDlfSecondEquipmentCount() {
		return this.dlfSecondEquipmentCount;
	}

	public void setDlfSecondEquipmentCount(Integer dlfSecondEquipmentCount) {
		this.dlfSecondEquipmentCount = dlfSecondEquipmentCount;
	}

	public Integer getDlfStatus() {
		return this.dlfStatus;
	}

	public void setDlfStatus(Integer dlfStatus) {
		this.dlfStatus = dlfStatus;
	}

	public String getDlfCreateUser() {
		return this.dlfCreateUser;
	}

	public void setDlfCreateUser(String dlfCreateUser) {
		this.dlfCreateUser = dlfCreateUser;
	}

	public Date getDlfCreateTime() {
		return this.dlfCreateTime;
	}

	public void setDlfCreateTime(Date dlfCreateTime) {
		this.dlfCreateTime = dlfCreateTime;
	}

	public String getDlfUpdateUser() {
		return this.dlfUpdateUser;
	}

	public void setDlfUpdateUser(String dlfUpdateUser) {
		this.dlfUpdateUser = dlfUpdateUser;
	}

	public Date getDlfUpdateTime() {
		return this.dlfUpdateTime;
	}

	public void setDlfUpdateTime(Date dlfUpdateTime) {
		this.dlfUpdateTime = dlfUpdateTime;
	}

	@Override
	public boolean equals(Object arg0) {
		if (arg0 != null && arg0 instanceof DeviceList1st) {
			DeviceList1st tp = (DeviceList1st) arg0;
			if (tp.getDlfId().equals(dlfId)) {
				return true;
			}
		}
		return false;
	}

	@Override
	public int hashCode() {
		return dlfId.hashCode();
	}

	@Override
	public String toString() {
		return dlfId  + " " +  dlfFirstEquipmentName;
	}

	public List<DeviceList2nd> getDevicList2ndList() {
		return devicList2ndList;
	}

	public void setDevicList2ndList(List<DeviceList2nd> devicList2ndList) {
		this.devicList2ndList = devicList2ndList;
	}
	
	public Set<DeviceList2nd> getDeviceList2ndSet(){
		Set<DeviceList2nd> set = new HashSet<DeviceList2nd>();
		set.addAll(devicList2ndList);
		
		return set;
	}
	
	public void setDeviceList2ndSet(Set<DeviceList2nd> set){
		devicList2ndList.clear();
		devicList2ndList.addAll(set);
	}

	public List<DeviceListDetail> getDeviceListDetailList() {
		return deviceListDetailList;
	}

	public void setDeviceListDetailList(List<DeviceListDetail> deviceListDetailList) {
		this.deviceListDetailList = deviceListDetailList;
	}
	
	public Set<DeviceListDetail> getDeviceListDetailSet(){
		Set<DeviceListDetail> set = new HashSet<DeviceListDetail>();
		set.addAll(deviceListDetailList);
		return set;
	}
	
	public void setDeviceListDetailSet(Set<DeviceListDetail> set){
		this.deviceListDetailList.clear();
		this.deviceListDetailList.addAll(set);
	}

}