package org.king.tender.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * DeviceList2nd generated by MyEclipse - Hibernate Tools
 */

public class DeviceList2nd extends org.king.framework.domain.BaseObject
		implements java.io.Serializable {

	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer dlsId;

	private Integer dlsFirstEquipmentId;

	private String dlsSecondEquipmentName;

	private Integer dlsThirdEquipmentCount;

	private Integer dlsStatus;

	private String dlsCreateUser;

	private Date dlsCreateTime;

	private String dlsUpdateUser;

	private Date dlsUpdateTime;
	
	private List<DeviceListDetail> deviceListDetailList = new ArrayList<DeviceListDetail>();

	// Constructors

	/** default constructor */
	public DeviceList2nd() {
	}

	/** minimal constructor */
	public DeviceList2nd(Integer dlsStatus) {
		this.dlsStatus = dlsStatus;
	}

	/** full constructor */
	public DeviceList2nd(Integer dlsFirstEquipmentId,
			String dlsSecondEquipmentName, Integer dlsThirdEquipmentCount,
			Integer dlsStatus, String dlsCreateUser, Date dlsCreateTime,
			String dlsUpdateUser, Date dlsUpdateTime) {
		this.dlsFirstEquipmentId = dlsFirstEquipmentId;
		this.dlsSecondEquipmentName = dlsSecondEquipmentName;
		this.dlsThirdEquipmentCount = dlsThirdEquipmentCount;
		this.dlsStatus = dlsStatus;
		this.dlsCreateUser = dlsCreateUser;
		this.dlsCreateTime = dlsCreateTime;
		this.dlsUpdateUser = dlsUpdateUser;
		this.dlsUpdateTime = dlsUpdateTime;
	}

	// Property accessors

	public Integer getDlsId() {
		return this.dlsId;
	}

	public void setDlsId(Integer dlsId) {
		this.dlsId = dlsId;
	}

	public Integer getDlsFirstEquipmentId() {
		return this.dlsFirstEquipmentId;
	}

	public void setDlsFirstEquipmentId(Integer dlsFirstEquipmentId) {
		this.dlsFirstEquipmentId = dlsFirstEquipmentId;
	}

	public String getDlsSecondEquipmentName() {
		return this.dlsSecondEquipmentName;
	}

	public void setDlsSecondEquipmentName(String dlsSecondEquipmentName) {
		this.dlsSecondEquipmentName = dlsSecondEquipmentName;
	}

	public Integer getDlsThirdEquipmentCount() {
		return this.dlsThirdEquipmentCount;
	}

	public void setDlsThirdEquipmentCount(Integer dlsThirdEquipmentCount) {
		this.dlsThirdEquipmentCount = dlsThirdEquipmentCount;
	}

	public Integer getDlsStatus() {
		return this.dlsStatus;
	}

	public void setDlsStatus(Integer dlsStatus) {
		this.dlsStatus = dlsStatus;
	}

	public String getDlsCreateUser() {
		return this.dlsCreateUser;
	}

	public void setDlsCreateUser(String dlsCreateUser) {
		this.dlsCreateUser = dlsCreateUser;
	}

	public Date getDlsCreateTime() {
		return this.dlsCreateTime;
	}

	public void setDlsCreateTime(Date dlsCreateTime) {
		this.dlsCreateTime = dlsCreateTime;
	}

	public String getDlsUpdateUser() {
		return this.dlsUpdateUser;
	}

	public void setDlsUpdateUser(String dlsUpdateUser) {
		this.dlsUpdateUser = dlsUpdateUser;
	}

	public Date getDlsUpdateTime() {
		return this.dlsUpdateTime;
	}

	public void setDlsUpdateTime(Date dlsUpdateTime) {
		this.dlsUpdateTime = dlsUpdateTime;
	}

	@Override
	public boolean equals(Object arg0) {
		if (arg0 != null && arg0 instanceof DeviceList2nd) {
			DeviceList2nd tp = (DeviceList2nd) arg0;
			if (tp.getDlsId().equals(dlsId)) {
				return true;
			}
		}
		return false;
	}

	@Override
	public int hashCode() {
		return dlsId.hashCode();
	}

	@Override
	public String toString() {
		return dlsId + " " + dlsSecondEquipmentName;
	}

	public List<DeviceListDetail> getDeviceListDetailList() {
		return deviceListDetailList;
	}

	public void setDeviceListDetailList(List<DeviceListDetail> deviceListDetailList) {
		this.deviceListDetailList = deviceListDetailList;
	}
	
	public Set<DeviceListDetail> getDeviceListDetailSet(){
		Set<DeviceListDetail> set = new HashSet<DeviceListDetail>();
		set.addAll(deviceListDetailList);
		return set;
	}
	
	public void setDeviceListDetailSet(Set<DeviceListDetail> set){
		this.deviceListDetailList.clear();
		this.deviceListDetailList.addAll(set);
	}

}